### ISSUE TITLE
Document geo features

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#142]
I would like to add geofeatures on a resource. I can read the discovery document and figure out how to do this myself, but it would be nice to have this on http://docs.thedatatank.com as well.

**Comment by coreation** [comment]
Geo-features are still a big pain to add in a custom way to a resource, shp has gone through a big rewrite and update making it so that almost every shape type is supported, using (and contributing to) existing libraries. However, adding geo-features to CSV, XLS, ... files will be quite an overhaul and a rare feature as well imo. Let alone the possible geographical coordinate system transformation that needs to go with it. I'll close this issue, if people have a non-shape file with geo properties that aren't defaulted by us (lat, long etc.) they'll need to make a custom resource and re-use code. For example:

* Read CSV using our CSV reader
* Merge certain columns that make up geographical properties
* Apply geographical transformation using existing imported libraries
* Tell the datatank it's a geographical dataset

So the person implementing this doesn't really need to do that much.
