### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by aborruso** [tdt/core#268]
Hi,
I have inserted this dataset in tdt:
http://webservices.rm.ingv.it/fdsnws/event/1/query?starttime=2014-12-30T00:00:00&minmag=2&format=text

It works and you can see it here (it's a very slow server):
http://muttley.spaziogis.it/datatank/core/public/italy/ingv/fdsnws

If I call XML output I have this error:
![2015-01-01_15h43_57](https://cloud.githubusercontent.com/assets/30607/5592389/1c10442c-91cd-11e4-9de2-31e1efc938a5.png)

I think because there special characters in source data. I'm writing here because it could be useful to add some routine that recognize these characters and solve automatically this output problem.

Thank you

**Comment by coreation** [comment]
That's because there's a tag starting with a number, according to the xml
spec, this is not allowed. However, since we just transform data into
different data formats, we have no clue on how to handle this, since this
is not handled in the spec (last time we checked ;) ).

On Thu, Jan 1, 2015 at 3:46 PM, Andrea Borruso <notifications@github.com>
wrote:

> Hi,
> I have inserted this dataset in tdt:
>
> http://webservices.rm.ingv.it/fdsnws/event/1/query?starttime=2014-12-30T00:00:00&minmag=2&format=text
>
> It works and you can see it here (it's a very slow server):
> http://muttley.spaziogis.it/datatank/core/public/italy/ingv/fdsnws
>
> If I call XML output I have this error:
> [image: 2015-01-01_15h43_57]
> <https://cloud.githubusercontent.com/assets/30607/5592389/1c10442c-91cd-11e4-9de2-31e1efc938a5.png>
>
> I think because there special characters in source data. I'm writing here
> because it could be useful to add some routine that recognize these
> characters and solve automatically this output problem.
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tdt/core/issues/268>.
>



-- 
Met vriendelijke groeten,

Jan Vansteenlandt
