### ISSUE TITLE
Add hydra metadata when output is triples

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#279]
Add the dcat triples to the document where the dataset is retrieved when we have output in RDF. Because that's the nice thing about RDF: we can add metadata about the document where we retrieve the data ;)

```
<{tdtbase}{tdt_id}> a dcat:Dataset ; 
                             dct:title "..." ;
                             dct:description "..." ; 
                             dcat:distribution <formatURI> .
...
<requestURI> void:subset <{tdtbase}{tdt_id}> ; hydra:nextPage <...?page=2>; hydra:firstPage <...> .
```

**Comment by coreation** [comment]
@pietercolpaert what exactly is <requestURI>? The (a) distribution?

**Comment by pietercolpaert** [comment]
The URL of the currently requested page

**Comment by coreation** [comment]
Ah, the example made me think this was a DCAT applicable only enhancement.

**Comment by pietercolpaert** [comment]
No... Whenever triples are returned, it would be nice to also include metadata for hypermedia clients :-)

**Comment by akuckartz** [comment]
:+1:

**Comment by coreation** [comment]
That could be nice yes, but when we read triples from file, 2 things can happen:

We read the file, all is well, it's not too big to show.
We read the file, stuff explodes because of memory being limited.

The first case doesn't really need a "nextPage" or "previousPage" which only is relevant when you order/sort the triples in some way, otherwise you'll (possible) always get different results when asking for the data.

The second case already stops before it begins, because the data is too big.

@pietercolpaert  Can you provide hydra meta-data that is always relevant for semantic data? (nextPage e.g. can be used when we use SPARQL, but not for every semantic datasource)

**Comment by coreation** [comment]
@pietercolpaert what about incorporating hydra paging triples in the Link header? This is how it works now since recently. Does that suffice or do you still argument to put the triples in the RDF body?

**Comment by pietercolpaert** [comment]
Yes, would love the triples in the RDF body as well. That's how it works. Even CKAN has it now: https://github.com/ckan/ckanext-dcat/blob/2899a42e83de0971d80b6bcc51fbfc40c93b7018/ckanext/dcat/processors.py#L182
