### ISSUE TITLE
DCAT validator 405 (access not allowed)

### ISSUE THREAD

**Issue by sebastienhenau** [tdt/core#313]
## Error
For the DCAT project for open Summer of code 2015 we use thedatatank to validate some files by URI, for example: "http://demo.thedatatank.com/dcat/demo.ttl". This link works correctly and does not show any errors. When we try to use other links from "dcat.be" like "http://datasets.antwerpen.be/v4/api/dcat" or "http://datatank4.gent.be/api/dcat" the validator returns a 405 error:
```
HEAD http://datatank4.gent.be/api/dcat 405 (Method Not Allowed)
```

## Testing
This error only shows when we are validating big files from the datatank. To make sure that the fault was not ours, we tested some big files in the URI and they got downloaded without showing any errors. We also used cURL to see if everything works and there were no errors. We added a function at our javascript file with jQuery called $.ajaxSetup where we defined a timeout. This did not work either. This way we wanted to prove that the 405 error was not on our side.

**Comment by coreation** [comment]
Hi @sebastienhenau a 405 error is never on your side as it's an HTTP response you get from the server. That being said, the "head" function is probably not implemented on the api/dcat URI you tried it on. That's because api/dcat is an API URI which mostly responds to GET and POST/PUT requests (not HEAD), whereas dataset URIs (such as dcat/demo.ttl) do have a HEAD implementation. 

Implementing a HEAD to check the availability is something we can do however. (thoughts @pietercolpaert )

**Comment by pietercolpaert** [comment]
I think we should indeed support HEAD.

I'm not sure why the javascript code of @sebastienhenau  tests HEAD instead of GET

**Comment by coreation** [comment]
HEAD is implemented on resources, now on DCAT as well.
