### ISSUE TITLE
Unit tests fail for 5.6.1

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/core#315]
I followed the steps described on http://docs.thedatatank.com/5.6/configuration on a fresh installation of TDT. No adjustments have been made to code, I am on v5.6.1 (adbd5a7).

```
Configuration read from /var/www/tdt/core/phpunit.xml

.............................E................................... 65 / 93 ( 69%)
...................E........

Time: 18.2 seconds, Memory: 95.50Mb

There were 2 errors:

1) Tdt\Core\Tests\Api\ShpTest::testGetApi
ErrorException: Undefined index: osm_id

/var/www/tdt/core/app/Tdt/Core/DataControllers/SHPController.php:121
/var/www/tdt/core/app/Tdt/Core/Datasets/DatasetController.php:80
/var/www/tdt/core/app/Tdt/Core/ApiController.php:38
/var/www/tdt/core/app/Tdt/Core/Tests/Api/ShpTest.php:69

2) Tdt\Core\Tests\Commands\ExportImportTest::testImportDefinitions
ErrorException: Undefined index: osm_id

/var/www/tdt/core/app/Tdt/Core/Repositories/TabularColumnsRepository.php:57
/var/www/tdt/core/app/Tdt/Core/Repositories/TabularBaseRepository.php:32
/var/www/tdt/core/app/Tdt/Core/Repositories/DefinitionRepository.php:40
/var/www/tdt/core/app/Tdt/Core/Definitions/DefinitionController.php:60
/var/www/tdt/core/app/Tdt/Core/ApiController.php:35
/var/www/tdt/core/app/Tdt/Core/Commands/Ie/Definitions.php:48
/var/www/tdt/core/app/Tdt/Core/Tests/Commands/ExportImportTest.php:126
                                      
FAILURES!                             
Tests: 93, Assertions: 451, Errors: 2.
```

**Comment by coreation** [comment]
Hi @DieterDePaepe , thanks for the heads-up, i'll check out what's wrong!

**Comment by coreation** [comment]
Strange, the travis CI seems to be working fine, what OS are you running it on?

**Comment by DieterDePaepe** [comment]
I tested this on a VM x64 Ubuntu 14.04.3 LTS (fresh install) using VirtualBox 4.3.30. My host OS is win 7 enterprise 64bit.

I'm guessing here, but could it be that the error is about some database index which could be present on the CI, but not applied when doing a fresh checkout?

**Comment by coreation** [comment]
osm_index is a column name of a shape file if I'm correct. So maybe either the reading of those files changed, or something in the file changed that we didn't pick up in the tests.

**Comment by coreation** [comment]
So this remains strange, you get the osm_id column still, so the data is there, yet the test don't find them. All that while my and travis' tests run 100% ok. I don't like voodoo ;)

**Comment by DieterDePaepe** [comment]
Just to be sure, I reran the other commands related to testing.

```
$ php artisan migrate --env=testing
Nothing to migrate.

$ php artisan migrate --env=testing --package=cartalyst/sentry
Nothing to migrate.

$ php artisan db:seed --env=testing
[Cartalyst\Sentry\Users\UserExistsException]                                 
  A user already exists with login [everyone], logins must be unique for users. 
```

After this, the unit tests still give erros, as listed in my original post.

**Comment by coreation** [comment]
Seems like after the release of 5.6.1 we cured some of these problems as we went on. The problem with the osm_id was due to unicode characters (which aren't readable) came out of the reader. We removed these in later commits. The testing of the DCAT feed has also been changed to a more specific testing function instead of just counting triples. Copying both solutions that are currently in the repo into the tag solved the issues. I'm going to look how I can create a new tag without breaking too much stuff (not being forced to use a different minor version number)

**Comment by coreation** [comment]
Done, unfortunately I couldn't merge a certain commit through a pull request, but that's only a small dirty spot on things. :) Check it out (here)[https://github.com/tdt/core/releases/tag/v5.6.2], just downloaded and tested it, turns out ok. Don't forget to composer update, because there's extra dependencies involved.
