### ISSUE TITLE
Failed to open demo shapefile

### ISSUE THREAD

**Issue by rossjones** [tdt/core#371]
When I visit the sample dresden/rivers dataset I get the following exception.  ~~Presumably it's a namespace problem (although I don't really know PHP so I guessing).~~ I guess this is a missing installation step for installing the extension that handles dbase_open.

```
Message Call to undefined function muka\ShapeReader\dbase_open() Class 
/var/www/core/vendor/muka/shape-reader/src/DbfFile.php On Line 60 Trace #0 [internal function]: 
Illuminate\Exception\Handler->handleShutdown() #1 {main}
```

After running ```sudo pecl install dbase``` and loading the extension, the error changes to 
```Could not find a supported EPSG code```.

**Comment by coreation** [comment]
Hi,

Indeed you missed a step in the installation, but you got that figured out :)
I think the complete seeding step was missing on your installation, perhaps missing database config during the installation step or a --no-scripts option. 

The error you're getting is because the EPSG codes are not seeded, try running 

```
php artisan db:seed --class=DcatSeeder
```

This will also fetch licenses and themes because there are necessary DCAT meta-data.
If these are already seeded and you only need to reseed the EPSG codes:

```
php artisan db:seed --class=GeoSeeder
```

We're using a 3rd party library to convert coordinates, it's been tested with a couple of belgian systems, UK and german ones.

**Comment by rossjones** [comment]
Perfect - thanks! Sorry for all the issues.

**Comment by coreation** [comment]
No problem, it's good feedback.
